version: '3.9'

services:
  web:
    container_name: web_container
    build:
      context: .
    entrypoint: bash
    command: >
      -c "cd /code/app && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - app.secrets.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres_network
    restart: unless-stopped

  db:
    container_name: db_container
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app.secrets.env
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
